### ISSUE TITLE
Configuration errors detected: unknown tag !<!secret>

### ISSUE THREAD

**Issue by latel** [avbor/HomeAssistantConfig#1]
errors happens while using this config:

[https://github.com/avbor/HomeAssistantConfig/blob/master/lovelace/views/vi_radio_quality_gw3.yaml]()

**Comment by avbor** [comment]
Just comment out this [lines](https://github.com/avbor/HomeAssistantConfig/blob/f610dbd83ab3b1614373572b2c4ab9806d65bad8/lovelace/views/vi_radio_quality_gw3.yaml#L117):
```
      - type: iframe
        url: !secret graf_url_zigbee_last_missed
        aspect_ratio: 10%
```
Or, put in your secrets.yaml url to graph.

**Comment by Xiaobin2333** [comment]
After comment out, will prompt: No card type found

**Comment by avbor** [comment]
secrets.yaml - part of Home Assistant, need to store passwords, tokens, etc
You can read about it [here](https://www.home-assistant.io/docs/configuration/secrets/).

>No card type found.
Can you post screenshot?
Custom flex-table-card installed?

**Comment by Xiaobin2333** [comment]
Thanks, this is my screenshot. flex-table-card has been installed through HACS.
![B8724B50-24BB-4DD0-A7AD-E344F0E6FA2F](https://user-images.githubusercontent.com/59763071/108587320-f4d33f00-738d-11eb-9327-41b22182ee0c.png)

**Comment by avbor** [comment]
If card correctly installed and HA rebooted after that, try reload lovelace and clear browser cache (Ctrl+F5).
No card type found - error related to card installation in HA.

**Comment by Xiaobin2333** [comment]
Try to install flex-table-card manually, the problem still persists.
Try the [flex-table-card example](https://github.com/custom-cards/flex-table-card/blob/master/docs/example-cfg-basics.md) can pass.
Could it be a problem with the ha version? Or is it the flex-table-card version?
thank you for your reply.Good luck and great success in the coming New Year.

**Comment by avbor** [comment]
>Could it be a problem with the ha version? Or is it the flex-table-card version?

I use it on latest HA version and flex-table-card installed from HACS.

How you copy code?
I think there is an extra space here, no?
![image](https://user-images.githubusercontent.com/32452033/108592403-cc901400-737e-11eb-8fb2-f47d0a77218c.png)


In my side it looks like that:
![image](https://user-images.githubusercontent.com/32452033/108592394-bd10cb00-737e-11eb-940c-b371776c558a.png)

>Good luck and great success in the coming New Year.

Thanks =)

**Comment by Xiaobin2333** [comment]
#I use it on latest HA version and flex-table-card installed from HACS.
Me too. 

#How you copy code?
I copy from [raw](https://raw.githubusercontent.com/avbor/HomeAssistantConfig/master/lovelace/views/vi_radio_quality_gw3.yaml).

#I think there is an extra space here, no?
This may be a font display problem,I also noticed this problem and try to re-enter. 

Thank you so much for your help. I am trying to find a solution to help people who have the same problem.

**Comment by avbor** [comment]
let me know if you can solve this problem.

**Comment by latel** [comment]
> Just comment out this [lines](https://github.com/avbor/HomeAssistantConfig/blob/f610dbd83ab3b1614373572b2c4ab9806d65bad8/lovelace/views/vi_radio_quality_gw3.yaml#L117):
> 
> ```
>       - type: iframe
>         url: !secret graf_url_zigbee_last_missed
>         aspect_ratio: 10%
> ```
> 
> Or, put in your secrets.yaml url to graph.

it's ok removing the following lines now
```
 - type: iframe
        url: !secret graf_url_zigbee_last_missed
        aspect_ratio: 10%
```
