### ISSUE TITLE
Problem with daikin_ir.h integration

### ISSUE THREAD

**Issue by Vortecsz** [avbor/HomeAssistantConfig#3]
Hey man, thank you so much for making your configuration public, I was trying to integrate the daikin_ir.h file with esphome, i copied your smartir configuration, and I tried to compile the file, but I get an error;
`In file included from src/main.cpp:54:
src/daikin_ir_v2.h:11:5: error: 'sensor' does not name a type
   11 |     sensor::Sensor *sensor_{nullptr};
      |     ^~~~~~
src/daikin_ir_v2.h:13:21: error: 'sensor' has not been declared
   13 |     void set_sensor(sensor::Sensor *sensor) { this->sensor_ = sensor; }
      |                     ^~~~~~
src/daikin_ir_v2.h:13:36: error: expected ',' or '...' before '*' token
   13 |     void set_sensor(sensor::Sensor *sensor) { this->sensor_ = sensor; }
      |                                    ^
src/daikin_ir_v2.h: In member function 'void DaikinAC::set_sensor(int)':
src/daikin_ir_v2.h:13:53: error: 'class DaikinAC' has no member named 'sensor_'
   13 |     void set_sensor(sensor::Sensor *sensor) { this->sensor_ = sensor; }
      |                                                     ^~~~~~~
src/daikin_ir_v2.h:13:63: error: 'sensor' was not declared in this scope; did you mean 'Sensor'?
   13 |     void set_sensor(sensor::Sensor *sensor) { this->sensor_ = sensor; }
      |                                                               ^~~~~~
      |                                                               Sensor
src/daikin_ir_v2.h: In member function 'virtual void DaikinAC::setup()':
src/daikin_ir_v2.h:17:17: error: 'class DaikinAC' has no member named 'sensor_'
   17 |       if (this->sensor_) {
      |                 ^~~~~~~
src/daikin_ir_v2.h:18:15: error: 'class DaikinAC' has no member named 'sensor_'
   18 |         this->sensor_->add_on_state_callback([this](float state) {
      |               ^~~~~~~
src/daikin_ir_v2.h:22:43: error: 'class DaikinAC' has no member named 'sensor_'
   22 |         this->current_temperature = this->sensor_->state;
      |                                           ^~~~~~~
src/daikin_ir_v2.h: In member function 'virtual esphome::climate::ClimateTraits DaikinAC::traits()':
src/daikin_ir_v2.h:106:53: error: 'class DaikinAC' has no member named 'sensor_'
  106 |       traits.set_supports_current_temperature(this->sensor_ != nullptr);
      |                                                     ^~~~~~~
*** [/data/ac-cucina/.pioenvs/ac-cucina/src/main.cpp.o] Error 1`

That's my configuration; 
`
esphome:
  name: ac-cucina
  friendly_name: AC-Cucina
  includes: 
    - include/daikin_ir_v2.h
  libraries:
    - IRremoteESP8266
esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: 

ota:
  password: 

wifi:
  ssid: 
  password: 

  ap:
    ssid: "Ac-Cucina Fallback Hotspot"
    password: "HrxpWj1hmHnY"

captive_portal:
 
remote_receiver:
  id: ir_receiver 
  pin:
    number: GPIO14
    inverted: True
    mode:
      input: true
      pullup: true
  tolerance: 55%
  dump: all
 
remote_transmitter:
  id: ir_transmit
  pin: GPIO4
  carrier_duty_percent: 50%
 
climate:
- platform: custom
  lambda: |-
    auto my_daikinac = new DaikinAC();
    App.register_component(my_daikinac);
    return {my_daikinac};

  climates:
    - name: "Living Room AC"
 
`

Would you be so kind as to give me a little help?
Thank you

**Comment by avbor** [comment]
Hi! Looks like you missed adding an external temperature sensor, it's needed for the climate platform to work properly:

**daikinac->set_sensor(id(ha_temp_${room_name}));**

```
sensor:
  - platform: homeassistant
    name: "Current temperature"
    entity_id: sensor.for_esphome_temp_in_${room_name}
    id: ha_temp_${room_name}
    internal: true
    unit_of_measurement: °C
    accuracy_decimals: 1

climate:
  - platform: custom
    lambda: |-
      auto daikinac = new DaikinAC();
      daikinac->set_sensor(id(ha_temp_${room_name}));
      App.register_component(daikinac);
      return {daikinac};
    climates:
      - name: "Daikin Nursery"
```

**Comment by Vortecsz** [comment]
Ohhh, my fault 
Ok the esp flashed successfully, but doesnt's seems to work with my ac ir;
`[16:15:04][D][remote.pronto:238]: Received Pronto: data=0000 006D 0044 0000 017B 0179 017A 0179 00B1 0060 000E 000E 000E 0024 000E 0024 000E 000E 000E 0024 000E 000E 000E 000E 000E 000E 000E 000E 000E 0024 000E 000E 000E 000E 000E 0024 000E 000E 000E 000E 000E 0025 000D 000E 000E 0025
[16:15:05][D][remote.pronto:240]: 000D 0025 000D 000F 000D 000F 000D 0025 000D 000F 000D 000F 000D 0025 000D 000F 000D 0025 000D 000F 000D 0025 000D 000F 000D 000F 000D 000F 000D 000F 000D 000F 000D 000F 000D 000F 000D 0025 000D 000F 000D 000F 000D 000F 000D 000F 000D 000F 000D 000F 000D 000F 000D 0025 000D 000F 000D 000F 000D 000F 000D 000F 000D 000F 000D 000F 000D 0025 000D 0025 000D 000F 000D 000F 000D 000F 000D 000F 000D 0025 000D 0025 000D 0025 000D 0025 000D 000F 000D 000F 000D 0025 000D 06C3`

What do you think? Is not compatible? I'm using an esp01_1m

**Comment by avbor** [comment]
Sorry, but I don't have any ideas other than going through different protocols. Maybe you should try the standard protocols from esphome (https://esphome.io/components/climate/climate_ir.html) or Arduino-HeatpumpIR (https://esphome.io/components/climate/climate_ir.html#arduino-heatpumpir). Daikin has a lot of different IR protocol implementations (https://github.com/crankyoldgit/IRremoteESP8266/blob/master/src/ir_Daikin.h).

**Comment by Vortecsz** [comment]
I'll try some of those thank you so much

**Comment by Vortecsz** [comment]
I'll try those thank you
