### ISSUE TITLE
RESTful Saures

### ISSUE THREAD

**Issue by lardeg** [avbor/HomeAssistantConfig#4]
Здравствуйте, пользуюсь вашей конфигурацией для счётчиков Saures после обновления Home Assistant счётчики не обновляются и стали вылазить такие ошибки в логах :

Error connecting https://api.saures.ru/1.0/object/meters failed with [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
Error connecting https://api.saures.ru/1.0/login failed with [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
Error connecting https://api.saures.ru/1.0/user/objects failed with [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

Как это можно исправить?

**Comment by avbor** [comment]
У меня прошло само ) перепроверил сертификаты, которые отдает api.saures.ru - сейчас никаких проблем не видно, может быть у них были какие-то проблемы.
